### ISSUE TITLE
Attribute error on compilation of kdl_parser

### ISSUE THREAD

**Issue by harsh1247** [colcon/colcon-core#167]
Compiling ros2 as per the documentation, Fails at kdl_parser
`Starting` >>> kdl_parser
--- stderr: kdl_parser                                                        
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/colcon_core/executor/__init__.py", line 91, in __call__
    rc = await self.task(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/colcon_core/task/__init__.py", line 92, in __call__
    return await task_method(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/colcon_ros/task/ament_cmake/build.py", line 72, in build
    return await extension.build(additional_hooks=additional_hooks)
  File "/usr/lib/python3.7/site-packages/colcon_cmake/task/cmake/build.py", line 93, in build
    .format_map(locals())
AttributeError: 'BuildPackageArguments' object has no attribute 'name'
---
Failed   <<< kdl_parser [ Exited with code 1 ] `
Please help

**Comment by dirk-thomas** [comment]
The stacktrace mentions [colcon-cmake](https://github.com/colcon/colcon-cmake).

Please include information what version of the colcon packages you are using (`colcon version-check`) and make sure to use the latest versions if not the case. Then please include the exact steps to reproduce the problem.

**Comment by dirk-thomas** [comment]
Closing due to no response.
