### ISSUE TITLE
Exception Sourcing local_setup.bat

### ISSUE THREAD

**Issue by allenh1** [colcon/colcon-core#242]
This seems to be new as of the last couple of days.

I cannot source my workspace on Windows 10.

```
G:\dashing_ws>call C:\ros2-windows\local_setup.bat
Traceback (most recent call last):
  File "C:\ros2-windows\_local_setup_util_bat.py", line 295, in <module>
    main()
  File "C:\ros2-windows\_local_setup_util_bat.py", line 49, in main
    args.additional_extension
  File "C:\ros2-windows\_local_setup_util_bat.py", line 179, in get_commands
    package_dsv_path, prefix, primary_extension, additional_extension)
  File "C:\ros2-windows\_local_setup_util_bat.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "C:\ros2-windows\_local_setup_util_bat.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "C:\ros2-windows\_local_setup_util_bat.py", line 199, in process_dsv_file
    type_, remainder, prefix)
  File "C:\ros2-windows\_local_setup_util_bat.py", line 264, in handle_dsv_types_except_source
    assert False, 'Unknown environment hook type: ' + type_
AssertionError: Unknown environment hook type: set
[connext_cmake_module] Warning: The location at which Connext was found when the workspace was built [[C:\Program Files\rti_connext_dds-5.3.1]] does not point to a valid directory, and the NDDSHOME environment variable has not been set. Support for Connext will not be available.
[opensplice_cmake_module] Warning: The location at which OpenSplice was found when the workspace was built [[C:\dev\opensplice\HDE\x86_64.win64\]] does not point to a valid directory, and the OSPL_HOME environment variable has not been set. Support for OpenSplice will not be available.
```

This seems to break the environment.

```
G:\dashing_ws>ros2 run rviz2 rviz2
Failed to load entry point 'info': DLL load failed: The specified module could not be found.
The C extension 'C:\ros2-windows\Lib\site-packages\rosbag2_transport\_rosbag2_transport_py.pyd' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'play': DLL load failed: The specified module could not be found.
The C extension 'C:\ros2-windows\Lib\site-packages\rosbag2_transport\_rosbag2_transport_py.pyd' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
Failed to load entry point 'record': DLL load failed: The specified module could not be found.
The C extension 'C:\ros2-windows\Lib\site-packages\rosbag2_transport\_rosbag2_transport_py.pyd' failed to be imported while being present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/#import-failing-even-with-library-present-on-the-system' for possible solutions
```

**Comment by dirk-thomas** [comment]
I assume you are either trying a nightly archive from Eloquent or building the latest state of master locally?

These packages already use a new feature (`.dsv` entries with the type `set`) to setup the environment more effiiciently. This needs the latest state of `colcon-core` which I just tagged and released as version 0.4.1.

Try running `colcon version-check` and if there are any updates install them (on Windows using `pip`). The problem should then be fixed after rebuilding any package in the workspace (which will regenerate the prefix level setup files.

If you are using the nightly archive from Jenkins you will need to wait for the next nightly archive.

**Comment by allenh1** [comment]
> If you are using the nightly archive from Jenkins you will need to wait for the next nightly archive.

This is exactly what I was doing.

Thanks @dirk-thomas, sorry for the noise.

**Comment by dirk-thomas** [comment]
No noise at all - it definitely needed a new release.
