### ISSUE TITLE
Colcon does not log where it's expected to

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#263]
Colcon logging options don't work as documented. It seems, contrary to the documentation, that:

1. `$COLCON_HOME ` is ignored for determining the logging location. Relative paths are always resolved relative to cwd. (in particular `COLCON_LOG_PATH is documented as defaulting to `$COLCON_HOME/log`, which is not the case)
2. `COLCON_LOG_PATH` handles `/dev/null` as documented, whereas `--log-base` crashes. This crash does not appear to produce log files anywhere.
3. Contrary to expectation, `COLCON_LOG_PATH` takes priority over the `--log-base` argument

```
$ colcon --help
...
optional arguments:
  -h, --help            show this help message and exit
  --log-base LOG_BASE   The base path for all log directories (default: log,
                        to disable: /dev/null)
  --log-level LOG_LEVEL
                        Set log level for the console output, either by
                        numeric or string value (default: warn)
...
Environment variables:
...
  COLCON_HOME           Set the configuration directory (default: ~/.colcon)
  COLCON_LOG_LEVEL      Set the log level (debug|10, info|20, warn|30,
                        error|40, critical|50, or any other positive numeric
                        value)
  COLCON_LOG_PATH       Set the log directory (default: $COLCON_HOME/log, to
                        disable: /dev/null)
```

test setup:
```
$ function logtest {
rm -rf /tmp/ws/ /tmp/colcon/ ~/.colcon/log
mkdir -p /tmp/ws/ /tmp/colcon/ ~/.colcon
cd /tmp/ws
eval ${1}
find ~/.colcon /tmp/colcon /tmp/ws -name log
}
```
test results (same in both zsh and bash):
```
$ logtest "colcon list"
/tmp/ws/log
$ logtest "COLCON_HOME=/tmp/colcon colcon list"
/tmp/ws/log
$ logtest "COLCON_HOME=/tmp/colcon colcon --log-base log list"
/tmp/ws/log
$ logtest "COLCON_HOME=/tmp/colcon COLCON_LOG_PATH=log colcon list"
/tmp/ws/log

$ logtest "COLCON_LOG_PATH=/dev/null colcon list"
$ logtest "colcon --log-base /dev/null list"
Traceback (most recent call last):
  File "/home/dan/.local/bin/colcon", line 8, in <module>
    sys.exit(main())
  File "/home/dan/.local/lib/python3.6/site-packages/colcon_core/command.py", line 161, in main
    create_log_path(args.verb_name)
  File "/home/dan/.local/lib/python3.6/site-packages/colcon_core/location.py", line 143, in create_log_path
    os.makedirs(str(path))
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/dev/null/list_2019-10-31_11-17-18'

$ logtest "COLCON_LOG_PATH=/tmp/colcon/log colcon list"
/tmp/colcon/log
$ logtest "colcon --log-base /tmp/colcon/log list"
/tmp/colcon/log
$ logtest "COLCON_LOG_PATH=log COLCON_HOME=/tmp/colcon colcon list"
/tmp/ws/log
$ logtest "COLCON_LOG_PATH=/tmp/colcon/env/log colcon --log-base /tmp/colcon/arg/log list"
/tmp/colcon/env/log
```

**Comment by dirk-thomas** [comment]
Thanks for the detailed report. Please see #264 which should resolve all three issues.

**Comment by rotu** [comment]
Sweet! Thanks!
