### ISSUE TITLE
Exception sourcing local_setup.bash

### ISSUE THREAD

**Issue by fujitatomoya** [colcon/colcon-core#266]
similar to https://github.com/colcon/colcon-core/issues/242

```
root@6cc2c62d0dd0:~/sony_colcon_ws# . install/local_setup.bash 
Traceback (most recent call last):
  File "/root/sony_colcon_ws/install/_local_setup_util_sh.py", line 295, in <module>
    main()
  File "/root/sony_colcon_ws/install/_local_setup_util_sh.py", line 49, in main
    args.additional_extension
  File "/root/sony_colcon_ws/install/_local_setup_util_sh.py", line 179, in get_commands
    package_dsv_path, prefix, primary_extension, additional_extension)
  File "/root/sony_colcon_ws/install/_local_setup_util_sh.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "/root/sony_colcon_ws/install/_local_setup_util_sh.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "/root/sony_colcon_ws/install/_local_setup_util_sh.py", line 199, in process_dsv_file
    type_, remainder, prefix)
  File "/root/sony_colcon_ws/install/_local_setup_util_sh.py", line 264, in handle_dsv_types_except_source
    assert False, 'Unknown environment hook type: ' + type_
AssertionError: Unknown environment hook type: set
```

then i did colcon version-check described https://github.com/colcon/colcon-core/issues/242.

```
root@6cc2c62d0dd0:~/sony_colcon_ws# colcon version-check
[130.252s] ERROR:colcon:colcon version-check: [Errno 99] Cannot assign requested address
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/command.py", line 442, in verb_main
    rc = context.args.main(context=context)
  File "/usr/lib/python3/dist-packages/colcon_devtools/verb/version_check.py", line 29, in main
    versions = pypi.package_releases(dist.project_name)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1112, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1452, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1154, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1166, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1279, in send_request
    self.send_content(connection, request_body)
  File "/usr/lib/python3.6/xmlrpc/client.py", line 1309, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1407, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 946, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
```

not sure what is going on here, is this because i am behind the proxy?

**Comment by dirk-thomas** [comment]
The solution described in the referenced ticket still applies and should solve your problem:

> These packages already use a new feature (`.dsv` entries with the type `set`) to setup the environment more effiiciently. This needs the latest state of colcon-core which I just tagged and released as version 0.4.1.

Regarding the stacktrace when invoking `version-check`: it could be related to your network setup. Please consider to fill a separate issue about it in https://github.com/colcon/colcon-devtools which implements the `version-check` verb if the problem persists.

Assuming that updating `colcon-core` resolves the original problem I am going to close this issue as a duplicate.

**Comment by fujitatomoya** [comment]
@dirk-thomas 

i got it fixed with updating colcon-core and refresh my environment.
sorry for making noise on this issue.

thanks

**Comment by Sleazey** [comment]
Reoccurrence on Windows 10:

C:\dev>call ros2_master\install\local_setup.bat
Traceback (most recent call last):
  File "C:\dev\ros2_master\install\_local_setup_util_bat.py", line 295, in <module>
    main()
  File "C:\dev\ros2_master\install\_local_setup_util_bat.py", line 49, in main
    args.additional_extension
  File "C:\dev\ros2_master\install\_local_setup_util_bat.py", line 179, in get_commands
    package_dsv_path, prefix, primary_extension, additional_extension)
  File "C:\dev\ros2_master\install\_local_setup_util_bat.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "C:\dev\ros2_master\install\_local_setup_util_bat.py", line 224, in process_dsv_file
    additional_extension=additional_extension)
  File "C:\dev\ros2_master\install\_local_setup_util_bat.py", line 199, in process_dsv_file
    type_, remainder, prefix)
  File "C:\dev\ros2_master\install\_local_setup_util_bat.py", line 264, in handle_dsv_types_except_source
    assert False, 'Unknown environment hook type: ' + type_
AssertionError: Unknown environment hook type: set

C:\dev>colcon version-check
colcon-cmake 0.2.17: up-to-date
colcon-core 0.4.5: up-to-date
colcon-defaults 0.2.2: up-to-date
colcon-devtools 0.2.2: up-to-date
colcon-library-path 0.2.1: up-to-date
colcon-metadata 0.2.2: up-to-date
colcon-notification 0.2.11: up-to-date
colcon-output 0.2.7: up-to-date
colcon-package-information 0.3.0: up-to-date
colcon-package-selection 0.2.5: up-to-date
colcon-parallel-executor 0.2.4: up-to-date
colcon-pkg-config 0.1.0: up-to-date
colcon-powershell 0.3.6: up-to-date
colcon-python-setup-py 0.2.2: up-to-date
colcon-recursive-crawl 0.2.0: up-to-date
colcon-ros 0.3.14: up-to-date
colcon-test-result 0.3.8: up-to-date

**Comment by dirk-thomas** [comment]
@Sleazey Please do not double post your question (which you already posted as #289).
