### ISSUE TITLE
Colcon build error on Windows while build ROS Dashing

### ISSUE THREAD

**Issue by DhruvKoolRajamani** [colcon/colcon-core#352]
Followed all the steps to build ROS2 Dashing on Windows 10. While performing the `colcon build --merge-install` I came across build errors for each package.

```bash
Failed   <<< poco_vendor        [ Exited with code 1 ]
[3.957s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['C:\\ros2_dashing\\build\\cyclonedds\\colcon_command_prefix_build.bat', '&&', 'set'] to pass
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\subprocess.py", line 107, in check_output
    assert not rc, 'Expected {args} to pass'.format_map(locals())
AssertionError: Expected ['C:\\ros2_dashing\\build\\cyclonedds\\colcon_command_prefix_build.bat', '&&', 'set'] to pass
```

This goes on for each package.

**Comment by dirk-thomas** [comment]
Please either modify your `colcon-core` code as proposed in #353 to improve the error message and post the updated error message or try to run the mentioned script `C:\\ros2_dashing\\build\\cyclonedds\\colcon_command_prefix_build.bat` directly and share its output.

**Comment by DhruvKoolRajamani** [comment]
I pulled the latest colcon-core and used that to run the code. I didn't notice anything different in the output. I'm pasting the complete error output and have attached the `logger_all` file.

```cmd
c:\dev\ros2_dashing>colcon build --merge-install
Starting >>> ament_package
Starting >>> ament_lint
Starting >>> osrf_testing_tools_cpp
Starting >>> fastcdr
Starting >>> poco_vendor
Starting >>> cyclonedds
Starting >>> ament_cppcheck
Starting >>> tinydir_vendor
Starting >>> gtest_vendor
Starting >>> osrf_pycommon
Starting >>> tinyxml2_vendor
Starting >>> orocos_kdl
[3.863s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\ament_package\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\ament_package\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.863s] colcon.colcon_ros.task.ament_python.build ERROR Could not find a shell extension for the command environment
Failed   <<< ament_package      [ Exited with code 1 ]
[3.864s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\ament_lint\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\ament_lint\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.864s] colcon.colcon_ros.task.ament_python.build ERROR Could not find a shell extension for the command environment
Failed   <<< ament_lint [ Exited with code 1 ]
[3.865s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\osrf_testing_tools_cpp\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\osrf_testing_tools_cpp\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.865s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
Failed   <<< osrf_testing_tools_cpp     [ Exited with code 1 ]
[3.896s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\fastcdr\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\fastcdr\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.897s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
Failed   <<< fastcdr    [ Exited with code 1 ]
[3.898s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\poco_vendor\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\poco_vendor\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.898s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
Failed   <<< poco_vendor        [ Exited with code 1 ]
[3.922s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\cyclonedds\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\cyclonedds\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.923s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
Failed   <<< cyclonedds [ Exited with code 1 ]
[3.947s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\ament_cppcheck\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\ament_cppcheck\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.948s] colcon.colcon_ros.task.ament_python.build ERROR Could not find a shell extension for the command environment
Failed   <<< ament_cppcheck     [ Exited with code 1 ]
[3.949s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\tinydir_vendor\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\tinydir_vendor\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.949s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
Failed   <<< tinydir_vendor     [ Exited with code 1 ]
[3.973s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\gtest_vendor\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\gtest_vendor\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.974s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
Failed   <<< gtest_vendor       [ Exited with code 1 ]
[3.998s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\osrf_pycommon\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\osrf_pycommon\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[3.999s] colcon.colcon_ros.task.ament_python.build ERROR Could not find a shell extension for the command environment
Failed   <<< osrf_pycommon      [ Exited with code 1 ]
[4.000s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['c:\\dev\\ros2_dashing\\build\\tinyxml2_vendor\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\python37\lib\site-packages\colcon_core\colcon_core\subprocess.py", line 110, in check_output
    'Expected {args} to pass: {stderr_data}'.format_map(locals())
AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\tinyxml2_vendor\\colcon_command_prefix_build.bat', '&&', 'set'] to pass: The system cannot find the path specified.


[4.000s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
Failed   <<< tinyxml2_vendor    [ Exited with code 1 ]
Aborted  <<< orocos_kdl

Summary: 0 packages finished [3.83s]
  11 packages failed: ament_cppcheck ament_lint ament_package cyclonedds fastcdr gtest_vendor osrf_pycommon osrf_testing_tools_cpp poco_vendor tinydir_vendor tinyxml2_vendor
  1 package aborted: orocos_kdl
  259 packages not processed
```

[logger_all.log](https://github.com/colcon/colcon-core/files/4664120/logger_all.log)

**Comment by dirk-thomas** [comment]
> I didn't notice anything different in the output.

The previous error message was:

    AssertionError: Expected ['C:\\ros2_dashing\\build\\cyclonedds\\colcon_command_prefix_build.bat', '&&', 'set'] to pass

The new error message is:

    AssertionError: Expected ['c:\\dev\\ros2_dashing\\build\\ament_package\\colcon_command_prefix_setup_py.bat', '&&', 'set'] to pass: The system cannot find the path specified.

Looking at the code this is surprising. The file is being created in line 122 but doesn't seem to exist in line 128 shortly afterwards:

https://github.com/colcon/colcon-core/blob/0371fe5b5e141f0c5ca7ee5b769845042b8cf2bb/colcon_core/shell/bat.py#L121-L128

Can you please check if the file(s) in question (e.g. `c:\\dev\\ros2_dashing\\build\\ament_package\\colcon_command_prefix_setup_py.bat`) exist. If they do please post their content as well as try to run them on the console and post the output.

**Comment by DhruvKoolRajamani** [comment]
> The new error message is:

Thanks for pointing that out, I guess I didn't spot that added exception message.

> Can you please check if the file(s) in question exist.

As I mentioned before, every build folder does contain the file but that file is empty. 

![](https://user-images.githubusercontent.com/35770744/82593782-007ca580-9b71-11ea-8691-f5bb8d30f2b0.png)

**Comment by dirk-thomas** [comment]
For some packages without dependencies it is expected that the file has only these two line. But other packages should have more content - lines like "call <script-from-dependency>". It looks like that not a single package finished to build and therefore no packages with dependencies have been processed yet.

How about running the full command:

```
c:\\dev\\ros2_dashing\\build\\ament_package\\colcon_command_prefix_setup_py.bat && set
```

**Comment by DhruvKoolRajamani** [comment]
> How about running the full command:

This shows me the output for `set`. 

Would you like to see the output of set?

**Comment by dirk-thomas** [comment]
Can you please call `echo %PATH%` on the console. If you get the same error message (`The system cannot find the path specified.`) I would guess that your `PATH` environment variable contains something wrong / invalid.

**Comment by DhruvKoolRajamani** [comment]
I don't seem to get any error when I echo path. However when I start a command shell I do see multiple `The system cannot find the path specified.`. I'm not sure if this has something to do with Path or other Environment Variables. I guess I could individually prune them but that could take time.

**Comment by DhruvKoolRajamani** [comment]
I found the broken Path. It wasn't in my system path rather in my local user path.
For any other people who come across a similar problem, this [answer](https://superuser.com/a/727323/1180641) helped me solve the problem.

Thanks for your help @dirk-thomas
