### ISSUE TITLE
Colcon doesn't try bash shell extension on Windows when running in bash

### ISSUE THREAD

**Issue by rotu** [colcon/colcon-core#372]
I'm using action-ros-ci on Windows to build. This runs the build inside Powershell (github runner) and bash shell (due to action-ros-ci)

There is a true mess of shells:
* the default shell for the environment is PowerShell
* vcvarsall is run under cmd https://github.com/rotu/colcon-cmake/runs/1029201058?check_suite_focus=true#step:17:405
* colcon is run inside bash

It seems Colcon detects the shell extension as 'bat' and doesn't even try to run the bash shell extension. I'm unclear if this is the intended behavior

```
[2236.713s] colcon.colcon_ros.task.ament_cmake.build INFO Building ROS package in 'D:\a\colcon-cmake\colcon-cmake\ros_ws\src\ros2\system_tests\test_rclcpp' with build type 'ament_cmake'
[2236.725s] colcon.colcon_cmake.task.cmake.build INFO Building CMake package in 'D:\a\colcon-cmake\colcon-cmake\ros_ws\src\ros2\system_tests\test_rclcpp'
[2236.738s] colcon.colcon_core.shell INFO Skip shell extension 'powershell' for command environment: Not usable outside of PowerShell
[2245.139s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['D:\\a\\colcon-cmake\\colcon-cmake\\ros_ws\\build\\test_rclcpp\\colcon_command_prefix_build.bat', '&&', 'set'] to pass
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.8\x64\lib\site-packages\colcon_core\shell\__init__.py", line 289, in get_command_environment
    task_name, Path(build_base), dependencies)
  File "c:\hostedtoolcache\windows\python\3.7.8\x64\lib\site-packages\colcon_core\shell\bat.py", line 128, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "c:\hostedtoolcache\windows\python\3.7.8\x64\lib\site-packages\colcon_core\shell\__init__.py", line 325, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "c:\hostedtoolcache\windows\python\3.7.8\x64\lib\site-packages\colcon_core\subprocess.py", line 106, in check_output
    assert not rc, 'Expected {args} to pass'.format_map(locals())
AssertionError: Expected ['D:\\a\\colcon-cmake\\colcon-cmake\\ros_ws\\build\\test_rclcpp\\colcon_command_prefix_build.bat', '&&', 'set'] to pass

[2245.139s] colcon.colcon_core.shell DEBUG Skip shell extension 'dsv' for command environment
[2245.139s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
```

```
  Starting >>> test_rclcpp
  [2245.139s] colcon.colcon_core.shell ERROR Exception in shell extension 'bat': Expected ['D:\\a\\colcon-cmake\\colcon-cmake\\ros_ws\\build\\test_rclcpp\\colcon_command_prefix_build.bat', '&&', 'set'] to pass
  Traceback (most recent call last):
    File "c:\hostedtoolcache\windows\python\3.7.8\x64\lib\site-packages\colcon_core\shell\__init__.py", line 289, in get_command_environment
      task_name, Path(build_base), dependencies)
    File "c:\hostedtoolcache\windows\python\3.7.8\x64\lib\site-packages\colcon_core\shell\bat.py", line 128, in generate_command_environment
      env = await get_environment_variables(cmd, cwd=str(build_base))
    File "c:\hostedtoolcache\windows\python\3.7.8\x64\lib\site-packages\colcon_core\shell\__init__.py", line 325, in get_environment_variables
      output = await check_output(cmd, cwd=cwd, shell=shell)
    File "c:\hostedtoolcache\windows\python\3.7.8\x64\lib\site-packages\colcon_core\subprocess.py", line 106, in check_output
      assert not rc, 'Expected {args} to pass'.format_map(locals())
  AssertionError: Expected ['D:\\a\\colcon-cmake\\colcon-cmake\\ros_ws\\build\\test_rclcpp\\colcon_command_prefix_build.bat', '&&', 'set'] to pass
  
  [2245.139s] colcon.colcon_cmake.task.cmake.build ERROR Could not find a shell extension for the command environment
  Failed   <<< test_rclcpp	[ Exited with code 1 ]
```

https://github.com/rotu/colcon-cmake/runs/1029201058?check_suite_focus=true#step:17:15252

**Comment by rotu** [comment]
The vagueness of the error message is a separate issue, documented in #371

**Comment by dirk-thomas** [comment]
> There is a true mess of shells:

Before calling a mess you might want to read about how these shell extensions work, the difference between a primary and non-primary shell, etc. See https://colcon.readthedocs.io/en/released/developer/environment.html?highlight=primary#different-shells

> It seems Colcon detects the shell extension as 'bat' and doesn't even try to run the bash shell extension. I'm unclear if this is the intended behavior

`colcon-bash` only targets non-Windows systems atm, see: https://github.com/colcon/colcon-bash/blob/cc1ae805dd921e7b40ead4dc69ff9a118c562c02/colcon_bash/shell/bash.py#L22-L23

> the default shell for the environment is PowerShell
> vcvarsall is run under cmd https://github.com/rotu/colcon-cmake/runs/1029201058?check_suite_focus=true#step:17:405
> colcon is run inside bash

PowerShell is only used for invoking command within colcon if `colcon` itself is invoked from PowerShell. Since you seems to invoke `colcon` from a `bash` shell it falls back to the only other alternative on Windows: `cmd`.

**Comment by rotu** [comment]
> Before calling something a mess you might want to read about how these shell extensions work

I don’t mean the shell extensions are a mess - the setup in the CI process is, which is why I felt the need to list them.

> colcon-bash only targets non-Windows systems atm

That’s the real head-scratcher. I fully expect colcon, if it uses a shell to use the *most proximate* shell, not skip a shell level. E.g. if I call colcon in zsh in bash in csh, I expect colcon to use the zsh shell extension. Since the innermost shell here is bash, I expect colcon to either run the bash shell extension or crash with an explanation that the shell extension is unsupported on the platform.

The bigger problem is that an executable generally should be agnostic about its parent shell (if any). It seems like colcon is incompatible with git-bash, wsl bash, cygwin, for no good reason. Even if the user wants to use the Python repl as a login shell, colcon should tolerate it.

> PowerShell is only used for invoking command within colcon if colcon itself is invoked from PowerShell

I get that. I think it’s undesirable that action-ros-ci changes the shell. Colcon gets this *right* by not using the Powershell extension; I don’t mean to imply otherwise.

**Comment by rotu** [comment]
As for the primary/non-primary shells, that’s an implementation decision, not a feature. Colcon *could* just walk the dsv files to create the variable environment for subprocesses, no shell scripts required.

You don’t even need to generate a tower of hooks and shell scripts; just a dsv interpreter that computes the final environment and exports it to a format that the parent shell can understand. Maybe something that can be invoked as, e.g., `eval “$(colcon export bash)”` or `colcon export bash > bin/local_setup.bash`

**Comment by dirk-thomas** [comment]
> I fully expect colcon, if it uses a shell to use the most proximate shell, not skip a shell level.

That is not what is happening here. The `colcon-bash` package was simply developed with only Linux / macOS in mind. If you would like to use it on Windows please consider to contribute a pull request removing this limitation.

> It seems like colcon is incompatible with git-bash, wsl bash, cygwin, for no good reason.

I have never tried either of them so I can't say if it works or what could be the cause for it. Again, please feel free to contribute to the project so support more use cases.

> As for the primary/non-primary shells, that’s an implementation decision, not a feature.

That is certainly not an implementation detail. The definition of an implementation detail is that from the outside you don't have to know about it. But a package which wants to contribute environment hooks does need to know about the difference since it should provide hooks for all primary shells, but doesn't have to provide hooks for non-primary shells.

> Colcon could just walk the dsv files to create the variable environment for subprocesses, no shell scripts required.

That would not be sufficient since packages might *only* provide shell scripts but no `.dsv` files.

**Comment by dirk-thomas** [comment]
This ticket (as previous ones you have created) is starting to get out of hand. There is no clear topic / focus and you are mentioning multiple different things. In this form it is more of a form (which the GitHub issue tracker isn't supposed to be used for) and not actionable.

Please keep the content of one ticket to a single specific bug / feature / use case in order to be able to clearly define the scope and desired actions.

**Comment by rotu** [comment]
> That is not what is happening here. The colcon-bash package was simply developed with only Linux / macOS in mind. If you would like to use it on Windows please consider to contribute a pull request removing this limitation.

Done. https://github.com/colcon/colcon-bash/pull/27

> That is certainly not an implementation detail. The definition of an implementation detail is that from the outside you don't have to know about it. But a package which wants to contribute environment hooks does need to know about the difference since it should provide hooks for all primary shells, but doesn't have to provide hooks for non-primary shells.

It *is* an implementation detail that happens to have functional implications. Maybe I don't understand: what hooks currently exist that behave differently based on the primary shell?

> This ticket (as previous ones you have created) is starting to get out of hand. There is no clear topic / focus and you are mentioning multiple different things. In this form it is more of a form (which the GitHub issue tracker isn't supposed to be used for) and not actionable.
> 
> Please keep the content of one ticket to a single specific bug / feature / use case in order to be able to clearly define the scope and desired actions.

Sorry. You're right I'm going off on tangents.

The goal here: If colcon is run in bash in cmd, it is expected to run bash-specific stuff.

That said, I don't understand why the behavior of colcon is dependent on the shell it runs in. If that were changed, this issue would be moot.

**Comment by dirk-thomas** [comment]
> I don't understand why the behavior of colcon is dependent on the shell it runs in.

In some cases `colcon` uses the primary shell which matches your environment (e.g. PowerShell vs. cmd) to setup the environment for packages and run commands. That is necessary since it a) can't assume the not used shell is even available (e.g. if the user uses cmd) and b) the current shell might offer necessary functionality not available in the other (e.g. if a user uses PowerShell and needs its support for long paths).

In the case of bash / zsh `colcon` doesn't care in which it is running because neither is a primary shell. It will use the primary shell `sh` to setup the environment for packages and run commands. The hooks of the primary shell are supposed to provide all necessary pieces. That is to avoid that a package has to duplicate the hooks for every imaginable `*sh` shell. Commonly the non-primary hooks only provide syntactic sugar (like completion) which isn't used / needed by `colcon` to perform the job.
