### ISSUE TITLE
Should depend on pytest

### ISSUE THREAD

**Issue by mikepurvis** [colcon/colcon-core#42]
Fresh install:

```$ /Users/mikepurvis/colcon_env/bin/colcon 
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.python_testing.pytest': No module named '_pytest'
Traceback (most recent call last):
  File "/Users/mikepurvis/colcon_env/lib/python3.6/site-packages/colcon_core/entry_point.py", line 86, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/Users/mikepurvis/colcon_env/lib/python3.6/site-packages/colcon_core/entry_point.py", line 128, in load_entry_point
    return entry_point.load()
  File "/Users/mikepurvis/colcon_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/Users/mikepurvis/colcon_env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/mikepurvis/colcon_env/lib/python3.6/site-packages/colcon_core/task/python/test/pytest.py", line 7, in <module>
    from _pytest.main import EXIT_NOTESTSCOLLECTED
ModuleNotFoundError: No module named '_pytest'

usage: colcon [-h] [--log-level LOG_LEVEL]
              {build,extension-points,extensions,info,list,metadata,test,test-result}
              ...

Error: No verb provided```

**Comment by dirk-thomas** [comment]
Thanks for the report. The problem has already been addressed in colcon/colcon-core#5 and will be part of the next release.

**Comment by mikaelarguedas** [comment]
Thanks @mikepurvis for reporting this.

This has been addressed in https://github.com/colcon/colcon-core/pull/5 and will be part of the next release.

**Comment by mikepurvis** [comment]
Ah, so I see. I took a quick look at recent commits but missed the fix. 👍

**Comment by mikepurvis** [comment]
Is the latest release usable, or is it best to try it from source? I'm running into some other random things which I won't bother trying to ticket if everything is still in flux anyway.

**Comment by dirk-thomas** [comment]
Since the last release several things have changes. On ci.ros2.org we use the latest state from the default branch. That should be working. A new release will hopefully be around next week.
