### ISSUE TITLE
Colcon is incopatible with `pyparsing` 3

### ISSUE THREAD

**Issue by KazNX** [colcon/colcon-core#451]
Hi,

I've just done a pip3 update and found this has broken colcon due to a version mismatch with `pyparsing`. Exception message below.

```
ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.environment_variable.defaults': (pyparsing 3.0.4 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('pyparsing<3,>=2.0.2'), {'packaging'})
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/colcon_core/entry_point.py", line 120, in load_entry_points
    extension_type = load_entry_point(entry_point)
  File "/usr/local/lib/python3.6/dist-packages/colcon_core/entry_point.py", line 168, in load_entry_point
    return entry_point.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2454, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2477, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 782, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyparsing 3.0.4 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('pyparsing<3,>=2.0.2'), {'packaging'})
```

**Comment by pablogs9** [comment]
+1 here. Any solution for that?

**Comment by mikepurvis** [comment]
Can either of you confirm that colcon _actually_ breaks with pyparsing 3.x, or was this just a semver best practices thing, to not assume that a new major version will always be safe to take? To check it, install colcon-core from source with that requirement dropped from the setup file.

Alternatively, try running colcon from a venv where you have a newer pip, since pip > 20.3 now has a backtracking-capable resolver that can detect and correct these situations.

**Comment by KazNX** [comment]
Some additional notes and steps to reproduce.

- As of yesterday it was fine on Ubuntu 20.04 because that was still fetching `pyparsing` version 2.4.6
- Locking `pyparsing` to 2.4.6 or 2.4.7 while upgrading `setuptools` works fine - e.g., use the following pip command to install colcon:
  - `pip3 install -U setuptools && pip3 install pyparsing==2.4.6 colcon-common-extensions`

Reproduction guide with docker

```bash
# Start a Unbutu 18.04 image
docker run --rm -it ubuntu:bionic /bin/bash
# Remaining commands run in the image:
apt update && apt install -y python3-pip
pip3 install colcon-common-extensions
# The following command will fail `pyparsing` version checks.
colcon --help
```

**Comment by KazNX** [comment]
@mikepurvis

> Can either of you confirm that colcon actually breaks with pyparsing 3.x

Unfotunately I cannot. While I can see this is an early versioning check validation failure, rather than a runtime error, I am not familiar enough with the python ecosystem to understand where the version check is configured. I dug around yesteray to no avail. As such, I'm not familiar enough with how to circumvent the version check and try running with version 3.

**Comment by mikepurvis** [comment]
@KazNX Per my previous message: "To check it, install colcon-core from source with that requirement dropped from the setup file."

**Comment by Acuadros95** [comment]
I am getting the same error, but this is a dependency from the `packaging 21.1` packet: [detail](https://github.com/pypa/packaging/blob/21.1/setup.py#L51)
Anyway, they are aware of this problem and should be fixed soon on a new release: https://github.com/pypa/packaging/issues/481

**Comment by akiragg** [comment]
一些額外的註釋和步驟來重現。

截至昨天，它在 Ubuntu 20.04 上很好，因為它仍在獲取pyparsing2.4.6 版
pyparsing升級時鎖定到 2.4.6 或 2.4.7setuptools可以正常工作 - 例如，使用以下 pip 命令安裝 colcon：
pip3 install -U setuptools && pip3 install pyparsing==2.4.6 colcon-common-extensions
帶 docker 的複制指南

#啟動一個 Unbutu 18.04 鏡像 docker 
run --rm -it ubuntu:bionic /bin/bash #在鏡像中運行剩餘的命令： 
apt update && apt install -y python3-pip
pip3 install colcon-common-extensions #以下命令將未能通過 `pyparsing` 版本檢查。
colcon --help

**Comment by pablogs9** [comment]
@Acuadros95 https://github.com/pypa/packaging/issues/481 is closed but this issue continues. Any idea?

**Comment by Acuadros95** [comment]
@pablogs9 The fix is not released yet, see https://github.com/pypa/packaging/issues/483
