### ISSUE TITLE
Exception in discovery with mixed ROS1/ROS2 prefix_path

### ISSUE THREAD

**Issue by markpaters** [colcon/colcon-core#502]
I am trying to build the ROS1/ROS2 bridge as described [here](https://github.com/ros2/ros1_bridge/blob/foxy/README.md). As part of this process, prefix_path ends up containing a mix of ROS1 and ROS2 install paths. During discovery, colcon (0.8.1) throws an exception:

> [0.222s] ERROR:colcon.colcon_core.package_discovery:Exception in package discovery extension 'prefix_path': object of type 'NoneType' has no len()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/package_discovery/__init__.py", line 250, in _discover_packages
    descs = extension.discover(
  File "/usr/lib/python3/dist-packages/colcon_installed_package_information/package_discovery/prefix_path.py", line 30, in discover
    num_packages = len(packages)
TypeError: object of type 'NoneType' has no len()

A bit of debug shows that what's happening is that find_installed_packages() returns None when it hits a ROS1 install path component. discover() should likely handle this case explicitly and not assume that it can call len() on the return value.

**Comment by markpaters** [comment]
Moving this to colcon-installed-package-information, since this is where the bug is.
