### ISSUE TITLE
Colcon build -> env: Argument list too long

### ISSUE THREAD

**Issue by danicannt** [colcon/colcon-core#558]
Hi,

I am trying to compile Autoware in a computer that uses ROS2 Galactic and Ubuntu20,
The computer is using Python 3.8.10
I've been able to make it work successfully in other computers that we have around but I have two where I tried and I am getting the exact same errors when I try.
```

[6.152s] ERROR:colcon.colcon_core.shell:Exception in shell extension 'sh': Expected ['.', '/home/dcanton/source/external/autoware/build/tier4_auto_msgs_converter/colcon_command_prefix_build.sh', '&&', 'env'] to pass: /bin/sh: 1: env: Argument list too long

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 302, in get_command_environment
    return await extension.generate_command_environment(
  File "/usr/lib/python3/dist-packages/colcon_core/shell/sh.py", line 154, in generate_command_environment
    env = await get_environment_variables(cmd, cwd=str(build_base))
  File "/usr/lib/python3/dist-packages/colcon_core/shell/__init__.py", line 338, in get_environment_variables
    output = await check_output(cmd, cwd=cwd, shell=shell)
  File "/usr/lib/python3/dist-packages/colcon_core/subprocess.py", line 128, in check_output
    assert not rc, f'Expected {args} to pass: {stderr_data}'
AssertionError: Expected ['.', '/home/dcanton/source/external/autoware/build/tier4_auto_msgs_converter/colcon_command_prefix_build.sh', '&&', 'env'] to pass: /bin/sh: 1: env: Argument list too long


[6.152s] ERROR:colcon.colcon_cmake.task.cmake.build:Could not find a shell extension for the command environment
```

Have this happened to anyone before?.
Thanks!

**Comment by cottsay** [comment]
Please take a look at #485, which exhibited the same symptom. In that case, the problem originated in the user's environment variable setup within their bash profile.

**Comment by danicannt** [comment]
Could you please give me some more info?

 I get that there is some problem with some environment variable ($PATH?) but I don't how did you be able to fix it
