### ISSUE TITLE
Intermittent StopIteration Error During Build on Ubuntu 22.04 (Iron)

### ISSUE THREAD

**Issue by lolddohaja** [colcon/colcon-core#629]
Hello colcon-core team,

I've been encountering an intermittent issue while building with colcon on Ubuntu 22.04 (Iron). Occasionally, during the build process, I receive a StopIteration error related to package augmentation for Python. Here's the error message:

```bash
colcon build
[27.097s] ERROR:colcon.colcon_core.package_augmentation:Exception in package augmentation extension 'python':
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/colcon_core/package_augmentation/__init__.py", line 97, in augment_packages
    retval = extension.augment_packages(
  File "/usr/lib/python3/dist-packages/colcon_installed_package_information/package_augmentation/python.py", line 44, in augment_packages
    dist = next(iter(dists))
StopIteration
```

Interestingly, this doesn't always prevent the build from completing. At times, deleting the build, log, and install directories and attempting the build process again seems to work.

I'm seeking insight into what might be causing this sporadic behavior. Is there a known issue with package augmentation in this context, or could there be a misconfiguration on my part? Any advice on troubleshooting steps or permanent fixes would be greatly appreciated.

Thank you for your assistance!

**Comment by jalenzz** [comment]
Ubuntu 22.04 humble has the same problem
