### ISSUE TITLE
Fail to build colcon (second time) on debian.

### ISSUE THREAD

**Issue by Theosakamg** [colcon/colcon-core#83]
Hello colcon team,

On Debian Buster (Testing)
with documentation : http://colcon.readthedocs.io/en/released/developer/bootstrap.html

after first build (all is ok), but the second build return :
```
~/ros_workspace/colcon_ws$ . install/local_setup.sh 
~/ros_workspace/colcon_ws$ colcon build
Traceback (most recent call last):
  File "~/ros_workspace/colcon_ws/install/colcon-core/bin/colcon", line 6, in <module>
    from pkg_resources import load_entry_point
  File "~/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3098, in <module>
    @_call_aside
  File "~/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3082, in _call_aside
    f(*args, **kwargs)
  File "~/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3111, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "~/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 573, in _build_master
    ws.require(__requires__)
  File "~/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 891, in require
    needed = self.resolve(parse_requirements(requirements))
  File "~/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest-runner' distribution was not found and is required by colcon-core
```

after install "pytest-runner" with :
```
~/ros_workspace/colcon_ws$ pip3 install pytest-runner
Collecting pytest-runner
  Downloading https://files.pythonhosted.org/packages/72/a4/d7a5738a3096f22a98bec1609e237b250ebff04e5ea2930305d485337263/pytest_runner-4.2-py2.py3-none-any.whl
Installing collected packages: pytest-runner
Successfully installed pytest-runner-4.2
```
Second build work.
I think you need to add "pytest-runner" to "requirements.txt"

**Comment by Theosakamg** [comment]
Based on an old installation of ROS2 ament / colcon(from deb).
I started this section: http://colcon.readthedocs.io/en/released/developer/bootstrap.html#fetch-the-sources

Not apply (can be the error ?) :
$ pip install vcstool
$ pip install -U pip setuptools

I apply :
```
$ apt-get remove --purge colcon*
$ mkdir colcon_ws
$ cd colcon_ws
$ curl --output colcon.repos https://raw.githubusercontent.com/colcon/colcon.readthedocs.org/master/colcon.repos
$ mkdir src
$ vcs import src < colcon.repos
$ touch src/colcon-powershell/COLCON_IGNORE
$ curl --output requirements.txt https://raw.githubusercontent.com/colcon/colcon.readthedocs.org/master/requirements.txt
$ pip3 install -r requirements.txt
$ ./src/colcon-core/bin/colcon build --paths src/*
```

Context :
(after the `pip3 install pytest-runner` )
```
$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
```
```
$ python3 -m easy_install --version
setuptools 40.0.0 from ~/.local/lib/python3.6/site-packages (Python 3.6)
```
```
$ pip3 list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
acme (0.25.1)
alabaster (0.7.10)
alembic (0.9.7.dev0)
argcomplete (1.9.4)
asn1crypto (0.24.0)
atomicwrites (1.1.5)
attrs (18.1.0)
Automat (0.6.0)
Babel (2.5.1)
bcrypt (3.1.4)
beautifulsoup4 (4.6.0)
binwalk (2.1.1)
blinker (1.4)
Brlapi (0.6.7)
bsddb3 (6.1.0)
catkin-pkg (0.4.5)
catkin-pkg-modules (0.4.6)
certbot (0.25.0)
certifi (2017.11.5)
chardet (3.0.4)
chrome-gnome-shell (0.0.0)
click (6.7)
colorama (0.3.7)
ConfigArgParse (0.13.0)
configobj (5.0.6)
constantly (15.1.0)
cov-core (1.15.0)
coverage (4.5.1)
cryptography (2.2.2)
cupshelpers (1.0)
cycler (0.10.0)
defer (1.0.6)
devscripts (2.18.3)
docopt (0.6.2)
docutils (0.14)
empy (3.3.2)
fail2ban (0.10.2)
flake8 (3.5.0)
Flask (1.0.2)
Flask-BabelEx (0.9.3)
Flask-Gravatar (0.4.2)
Flask-HTMLmin (1.3.2)
Flask-Login (0.4.1)
Flask-Mail (0.9.1)
Flask-Migrate (2.1.1)
Flask-Paranoid (0.2.0)
Flask-Principal (0.4.0)
Flask-Security (1.7.5)
Flask-SQLAlchemy (2.1)
Flask-WTF (0.14.2)
future (0.16.0)
gbp (0.9.9)
Glances (2.11.1)
gramps (4.2.8)
htmlmin (0.1.12)
httplib2 (0.9.2)
hyperlink (17.3.1)
idna (2.6)
imagesize (0.7.1)
incremental (16.10.1)
itsdangerous (0.24)
javalang (0.11.0)
javasphinx (0.9.15)
Jinja2 (2.10)
josepy (1.1.0)
kiwisolver (1.0.1)
louis (3.6.0)
lxml (4.1.1)
Mako (1.0.7)
Markdown (2.6.9)
MarkupSafe (1.0)
matplotlib (2.2.2)
mccabe (0.6.1)
meld (3.18.2)
menulibre (2.2.0)
mock (2.0.0)
more-itertools (4.2.0)
mousetrap (3.17.3)
Nautilus-scripts-manager (2.0)
netifaces (0.10.4)
nose (1.3.7)
nose2 (0.7.4)
notify2 (0.3.1)
numpy (1.14.5)
nyx (2.0.4)
olefile (0.45.1)
onionshare (1.3)
openshot-qt (2.4.1)
packaging (17.1)
paramiko (2.4.0)
parsedatetime (2.4)
passlib (1.7.1)
path-and-address (2.0.1)
pbr (3.1.1)
pep8 (1.7.1)
pexpect (4.6.0)
Pillow (4.3.0)
pip (9.0.1)
pluggy (0.6.0)
protobuf (3.0.0)
psutil (5.4.6)
psycopg2 (2.7.5)
py (1.5.4)
pyasn1 (0.4.2)
pyasn1-modules (0.2.1)
pycairo (1.16.2)
PyChromecast (0.8.1)
pycodestyle (2.3.1)
pycrypto (2.6.1)
pycups (1.9.73)
pycurl (7.43.0.1)
pydocstyle (2.1.1)
pyflakes (1.6.0)
Pygments (2.2.0)
pygobject (3.28.2)
PyNaCl (1.2.1)
pyOpenSSL (18.0.0)
pyparsing (2.2.0)
pyRFC3339 (1.1)
pyserial (3.4)
pysmbc (1.0.15.6)
pytest (3.6.3)
pytest-cov (2.5.1)
pytest-repeat (0.4.1)
pytest-rerunfailures (4.1)
pytest-runner (4.2)
python-apt (1.6.2)
python-dateutil (2.7.3)
python-debian (0.1.32)
python-debianbts (2.7.2)
python-editor (0.4)
python-xlib (0.20)
pytz (2017.3)
pyxdg (0.25)
PyYAML (3.13)
pyzmq (17.0.0)
reportbug (7.5.0)
reportlab (3.4.0)
requests (2.18.4)
requests-toolbelt (0.8.0)
roman (2.0.0)
scour (0.36)
service-identity (16.0.0)
setuptools (40.0.0)
simplejson (3.15.0)
six (1.11.0)
snowballstemmer (1.2.1)
Sphinx (1.6.5)
sphinxcontrib-websupport (1.0.1)
SQLAlchemy (1.2.8)
sqlparse (0.2.4)
sshtunnel (0.1.4)
stem (1.6.0)
Twisted (18.4.0)
unattended-upgrades (0.1)
urllib3 (1.22)
vboxapi (1.0)
vcstool (0.1.36)
Werkzeug (0.14.1)
wheel (0.30.0)
WTForms (2.1)
youtube-dl (2018.6.18)
zeroconf (0.19.1)
zope.component (4.3.0)
zope.event (4.2.0)
zope.hookable (4.0.4)
zope.interface (4.3.2)
```

**Comment by dirk-thomas** [comment]
Thank you for the additional information. I can reproduce your problem and added the dependency as suggested in colcon/colcon.readthedocs.org#27. It looks like it was forgotten to update when this `install_requires` was added recently in #72.

I double checked the other packages to ensure nothing else was missing.
